blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/mikeg-dal/QK4/discussions
    about: Ask questions or discuss ideas that aren't a concrete bug report or feature request.
